# Generated by Django 4.0.4 on 2022-07-01 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0004_alter_docente_nacimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docente',
            options={'verbose_name': 'docente', 'verbose_name_plural': 'docentes'},
        ),
    ]
