# Generated by Django 4.0.4 on 2022-07-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0005_alter_docente_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='docentes'),
        ),
    ]
