# Generated by Django 4.0.4 on 2022-06-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=120)),
                ('consulta', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
