# Generated by Django 4.0.4 on 2022-06-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0002_contacto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.AlterField(
            model_name='carrera',
            name='carrera',
            field=models.CharField(max_length=90, unique=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='materia',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
