# Generated by Django 4.0.4 on 2022-06-06 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0003_delete_alumno_alter_carrera_carrera_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Docente',
        ),
    ]
