# Generated by Django 4.0.4 on 2022-06-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0004_delete_docente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='descripcion',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='duracion',
            field=models.CharField(max_length=30),
        ),
    ]
