# Generated by Django 4.0.4 on 2022-06-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alter_alumno_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='nacimiento',
            field=models.DateField(),
        ),
    ]
