# Generated by Django 4.0.4 on 2022-07-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_alter_alumno_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='alumnos'),
        ),
    ]
