# Generated by Django 4.0.4 on 2022-06-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=90, unique=True)),
                ('descripcion', models.CharField(max_length=90)),
                ('cantidad_de_materias', models.IntegerField()),
                ('duracion', models.CharField(max_length=30)),
                ('cantidad_de_alumnos', models.CharField(max_length=30)),
                ('docente', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=120)),
                ('consulta', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
