# Generated by Django 4.0.4 on 2022-07-01 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrera',
            options={'verbose_name': 'carrera', 'verbose_name_plural': 'carreras'},
        ),
    ]
