# Generated by Django 4.0.4 on 2022-07-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0002_alter_carrera_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='carreras'),
        ),
    ]
